Repository a11yproject/a11yproject.com, pull requests merged in 2018-11, with the labels that each got.

#666 [Article] Quick test: Large touch targets
  _data/authors.yml
  _posts/2018-11-21-large-touch-targets.md
  img/posts/2018-11-21-large-touch-targets/touch-target-inspector.png
  img/posts/2018-11-21-large-touch-targets/touch-target-padding.svg
Labels: Article

#671 Add a11y nottingham event
  _data/events.yml
Labels: Events

#673 Myth: Accessibility is blind people article updates
  _posts/2013-01-11-myth-accessibility-is-blind-people.md
Labels: Article Audit

#677 Quick tip: Never use maximum-scale=1.0 article updates
  _posts/2013-01-14-never-use-maximum-scale.md
Labels: Article Audit

#675 Quick test: Check comprehension level article edits
  _posts/2013-01-25-check-comprehension-level.md
Labels: Article Audit

#676 Quick test: Check contrast with your mobile device article edits
  _posts/2013-01-22-check-contrast-with-mobile-device.md
Labels: Article Audit

#681 updates for Safari keyboard navigation article
  _posts/2017-12-29-safari-keyboard-navigation.md
Labels: Article Audit

#679 revisions to using alt text article
  _posts/2013-01-14-alt-text.md
Labels: Article Audit
