Repository a11yproject/a11yproject.com, pull requests merged in 2019-07, with the labels that each got.

#815 Add Gemfile and .ruby-version
  .ruby-version
  Gemfile
Labels: [Type] Enhancement

#818 Gulp error handling
  gulpfile.js
  package-lock.json
  package.json
Labels: Redesign

#822 Update resources.yml
  _data/resources.yml
Labels: [Content] Resource, [Type] Enhancement
