Repository a11yproject/a11yproject.com, pull requests merged in 2022-04, with the labels that each got.

#1434 Uses type=radio in theme toggle JS code
  src/js/theme-toggle.js
Labels: javascript

#1435 Add dark mode support announcement
  src/_includes/footer.njk
  src/announcements.njk
  src/announcements/dark-mode-support.md
  src/img/announcements/dark-mode-support/theme-switcher-dark.png
  src/img/announcements/dark-mode-support/theme-switcher-light.png
Labels: markup

#1438 Update resources
  src/_data/resources.json
Labels: resource, data
